### ISSUE TITLE
Sharing one index between several processes, over time.

### ISSUE THREAD

**Issue by Adoni5** [DaehwanKimLab/centrifuge#135]
Hi, I suppose this is less of issue and more of an open question.

I am trying to run several centrifuge processes over a period of time, but from only one index. So ideally I'd like to load the index and then have all the processes reference that one index during classification. I have limited memory and processing power, so I was looking at the --mm option. However I was a little unclear on how it works. 

Does using the --mm flag mean that a centrifuge-class process loads the index into memory and then any subsequent classification process use that pre-loaded index once that process is finished, or do they share it in real time? 

Once the classifications are finished I assume the index is removed from memory. Is there a way to leave it loaded?

Also, can someone explain how --mm works if the index doesn't fit into memory? Is the index placed into virtual memory instead?

I know that's a lot of questions, so I appreciate any help!

Thank you

Rory

**Comment by mourisl** [comment]
If you have root right, maybe you can try ramdisk as mentionedn in #65 .

**Comment by Adoni5** [comment]
Coming back to this #95 was the solution I needed. Thank you very much, sorry I never closed this!
