### ISSUE TITLE
Species and its subspecies/strain both appear in the centrifuge report

### ISSUE THREAD

**Issue by zifanzhu** [DaehwanKimLab/centrifuge#169]
Hi there,

I'm using centrifuge (v1.0.4-beta) to perform taxonomic profiling of a shotgun sequencing data. Here is a part of the report file I got:

![image](https://user-images.githubusercontent.com/28163733/55764289-cc532d80-5a1f-11e9-8d11-673016b8629e.png)

We see from the highlighted part that both species **_Lactococcus lactis_** and its subspecies appear in the report and get nonzero abundance. This makes me confused. From my understanding, reads mapped to a subspecies/strain could also be mapped to its corresponding species; thus, one should either group subspecies/strain abundance into its species or set species abundance to 0 and only keep its various subspecies/strain abundances. I wonder if there is any overlap in the abundances of **_Lactococcus lactis_** and its subspecies.

Really appreciate it if anyone can help!

Best,
Zifan

**Comment by mourisl** [comment]
Sorry for the late reply, Centrifuge does not group the abundances from sub species.

**Comment by zifanzhu** [comment]
Thanks for your reply!
