### ISSUE TITLE
Centrifuge with 16S database

### ISSUE THREAD

**Issue by LaraUrban** [DaehwanKimLab/centrifuge#171]
Hi,

I was wondering if you could help us with the following problem that we encounter when using Centrifuge classification: We wanted to classify our 16S rRNA reads sequence by Oxford Nanopore, and used Centrifuge and Kraken2 to do so while building a NCBI database based on all bacterial data and a 16S database based on the Silva database for both classification tools.
Whereas Kraken2 is able to classify most reads (>90%) with both bacterial NCBI and 16S database, Centrifuge only classifies comparably many reads if we take the bacterial NCBI database. In the case of the 16S database, very few reads (~10%) can be classified. I was wondering if you have any explanation for this effect?

Many thanks for your help!

Best regards,
Lara

**Comment by mourisl** [comment]
Since the 16S sequences is on the bacteria reference genome, it could be that by putting them together, the database becomes too repetitive. Can you try to use larger -k value?

**Comment by LaraUrban** [comment]
Many thanks @mourisl we will try a larger k

**Comment by LaraUrban** [comment]
Hi @mourisl, Unfortunately, increasing k did not change the percentage of classified reads. Do you have another idea? Many thanks!

**Comment by LaraUrban** [comment]
Also, just to clarify: We either use the 16S database or the bacterial database, never a combined version. Many thanks for any advice!

**Comment by LaraUrban** [comment]
PS: Even at k=1000, it only improves from ~5% classified reads (k=5) to 7%. @mourisl

**Comment by LaraUrban** [comment]
@mourisl sorry, any idea?

**Comment by LaraUrban** [comment]
Hi @mourisl,

As stated above, increasing k did not change the percentage of classified reads. If you do not have any other idea, I am not sure what to do besides stating in the manuscript that Centrifuge does not work for the 16S database. We will have to include the Centrifuge 16S since we also use Kraken 16S and Bracken 16S as well as their bacterial database counterparts. Please let me know what you think. 

Many thanks,
Lara

**Comment by mourisl** [comment]
Can I have your 16S database for Centrifuge? And can I also have a few Centrifuge unclassified but Kraken2 classified reads to debug? Thanks.

**Comment by mourisl** [comment]
I just noticed that for some 16S database, the reference sequence may use Uracil(U) instead of T. Is this for your case? Thanks.

**Comment by LaraUrban** [comment]
Many thanks @mourisl! The reference sequence contains T, not U, but many thanks for the suggestion. 

We are using the SILVA 16S database: https://www.arb-silva.de/

I will send you a read classified by Kraken2, but unclassified by Centrifuge (using the same SILVA database) via email. Thanks for looking into this.

**Comment by LaraUrban** [comment]
PS: I just sent you an email. Many thanks again!

**Comment by LaraUrban** [comment]
Hi @mourisl, 

Many thanks for your great help! For everyone: It turned out that we had been using the conversion table produced by Kraken2, and not by Centrifuge.

We will now rebuild the centrifuge 16S database, and include the Centrifuge classifications in our manuscript.

**Comment by mansi-aai** [comment]
Hello @LaraUrban !

I am trying to built SILVA 16s rRNA database to use centrifuge. I got the FASTA file from [SILVA website](https://www.arb-silva.de/no_cache/download/archive/release_138/Exports/) but I am not able to create conversion-table , taxonomy-tree and name-table which are required to build the database. Can you please let me know how did how created that ? Thank you ! 

Many Thanks,
Mansi
