### ISSUE TITLE
Question about DB building

### ISSUE THREAD

**Issue by fetyj** [DaehwanKimLab/centrifuge#173]
Hello, I have already build a custom database containing bacteria, virus and fungi. Unfortunately, I noticed that my database lack some representative genome...Is there a possibility to add some genomes to my (built) database or should I build it to the beginning (last time it took me one week...)
Thanks for your help,

Regards,
Fety

**Comment by mourisl** [comment]
Sorry, you need to rerun centrifuge-build in this case.

**Comment by fetyj** [comment]
Thanks for the reply, I will rerun centrifuge-build after several checks.
