### ISSUE TITLE
centrifuge-download - g option duplicated

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [DaehwanKimLab/centrifuge#175]
In the help section, -g option says specify program, AND download GI map. But download GI map is not implemented. How can this be done? Thanks.

**Comment by mourisl** [comment]
Thanks for letting us know. I've removed the -g for GI map from the usage. You can download the GI map file from ftp://ftp.ncbi.nih.gov/pub/taxonomy/ . But I'm not quite sure how Centrifuge would behave on the current gi format.

**Comment by theo-allnutt-bioinformatics** [comment]
Yes it does not work with the current format. It needs: accension.1 <space>
taxid. Gis do not work anymore.
