### ISSUE TITLE
centrifuge-build fails for unknown reason

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [DaehwanKimLab/centrifuge#178]
Hi, I have a 250 GB file of genomes that I want to build into an index. They are in the correct format as is the mapping file as far as I can tell. When I try to build on a 600 GB RAM machine, I get an error that is possibly RAM (I am using a batch system and can't check). Is this normal for this size of db? Thanks.

**Comment by mourisl** [comment]
My experience is that it takes about 3 times of the genome size as the memory to build the index. So you need about 750GB memory for this.

**Comment by trip23app** [comment]
> about 3 times of the genome size as the memory to build the

so update the issue title?
