### ISSUE TITLE
Centrifuge index not much smaller than input database FASTA

### ISSUE THREAD

**Issue by mmp3** [DaehwanKimLab/centrifuge#181]
I downloaded RefSeq genomes for bacteria (~15,000), archaea (~300), fungi (11), protozoa (3), and human. I also downloaded Genbank viral genomes (~33,000). Combined, this database is a 60 GB FASTA (uncompressed), of which 56 GB is the bacteria RefSeq genomes, and another 3 GB is the human genome.

`centrifuge-build` produced index files totaling ~37 GB. This is surprising because one major advantage of centrifuge is supposed to be its ability to make a condensed representation of the database that is small enough to be able to fit into memory e.g. on a standard laptop.

This is also surprising because this database is almost the same as the "p+h+v" database hosted on the [centrifuge website at JHU](https://ccb.jhu.edu/software/centrifuge/manual.shtml), yet the "p+h+v" database is only 11.3 GB uncompressed.

Why is the index so large? How can nearly the same database produce index files which are 3.5 times larger than the "p+h+v" database hosted on JHU?

Also, where is the option to build a "compressed" in `centrifuge-build`?  No such option is listed in the command line help, as far as I can tell.

Thank you!

**Comment by matthewParksViome** [comment]
good idea. i will build a "current" p+h+v index using the command you suggested and let you know what size it is.

**Comment by fanninpm** [comment]
> Note that the compression is fairly slow procedure.

Especially when it tries to compress an _Escherichia coli_ K-12 ER2796 chromosome that's roughly 100 times the size that it should be.
