### ISSUE TITLE
Please try again on a computer with more memory.

### ISSUE THREAD

**Issue by GrantHov** [DaehwanKimLab/centrifuge#184]
I am trying to map RNAseq data against the whole nt database with 96Gb of RAM and get the following error:

Please try again on a computer with more memory.

How much RAM should I have?
Thanks

**Comment by mourisl** [comment]
The memory requirement is roughly the same as the index file size. You probably need around 110G memory.

**Comment by GrantHov** [comment]
Thanks, will try it.
