### ISSUE TITLE
kraken-style report

### ISSUE THREAD

**Issue by chulghim** [DaehwanKimLab/centrifuge#202]
1)
Is the abundance value from kraken-style report normalized by its genomic length such as centrifuge-style report's seventh column?

2)
Which of numReads and numUniqReads do you use to calculate abundances?

**Comment by mourisl** [comment]
1. No, the abundance is not normalized by the genome length in report.
2. I think it is the numReads, which should be the number of reads from the subtree in the taxonomy tree with the current taxonomy id as the root.
