### ISSUE TITLE
Error in centrifuge 

### ISSUE THREAD

**Issue by akhalil2** [DaehwanKimLab/centrifuge#203]
Hallo 
I am trying to install centrifuge and i get error (ERR): centrifuge-class exited with value 1.. and when i build the indices and try my analysis i get Expected centrifuge to be in same directory with centrifuge-class)

**Comment by mourisl** [comment]
What was your command for running Centrifuge?

**Comment by akhalil2** [comment]
Sudo apt-get install centrifuge

**Comment by mourisl** [comment]
Could you please use "which centrifuge" to find the install path of Centrifuge, and check whether centrifuge-class, centrifuge-build are in that folder?

**Comment by akhalil2** [comment]
Centrifuge-build is here but class is not.

**Comment by mourisl** [comment]
You may try the github version, just git clone or download through the packages, then run "make". It should generate the centrifuge-class, -build files. And then you can run centrifuge from the "make" path.

**Comment by akhalil2** [comment]
iIt was my mistake. I had a typo in the command so it didn't work well
..the other mistake I reinstalled centrifuge and wrote centrifuge without
putting input so it gives me error .. thanks

‫في الخميس، 26 نوفمبر 2020 في 6:16 م تمت كتابة ما يلي بواسطة ‪Li Song‬‏ <‪
notifications@github.com‬‏>:‬
