### ISSUE TITLE
Issue with number of raw reads

### ISSUE THREAD

**Issue by mggrami** [DaehwanKimLab/centrifuge#206]
Hello!

I have a question regarding number of reads. My dataset contain:
103.425714 M of paired end reads. However after running centrifuge + centrifuge-kreport:

centrifuge -x ../database_bacteria_archaea_2018/p_compressed_2018_4_15/p_compressed -1 out_BY15_DNA1_1.fq.gz -2 out_BY15_DNA1_2.fq.gz -S centrifuge_BY15_class_results --report-file centrifuge_report_BY15.tsv --threads 12 
&&
 centrifuge-kreport -x ../database_bacteria_archaea_2018/p_compressed_2018_4_15/p_compressed centrifuge_BY15_class_results

It only gives me half of the total number of reads -> 51.712857 M

My question is:
Is it not reading the second file or is it combining reads together?
Sincerely,
Michal

**Comment by mourisl** [comment]
Centrifuge combines the mate pairs together.

**Comment by mggrami** [comment]
Thank You for the quick answer!
