### ISSUE TITLE
Issue with centrifuge-download (dustmaster: command not found)

### ISSUE THREAD

**Issue by lewhiteside** [DaehwanKimLab/centrifuge#237]
Hi there,

I am trying to download archaeal, bacterial, fungal and viral genomes into a library using the following command:

`centrifuge-download -o library -m -d "archaea,bacteria,viral,fungi" refseq > seqid2taxid.map`

The library folders are being created in my centrifuge folder, along with the .fna files.
However, the fna files are empty - and the following error appears 

`line28: dustmaster: command not found `

This is my first time using linux so I am very new!  Im not sure why this is coming up and I cant find any help online - 

Could someone please point me in the right direction of what is going wrong?  - and how I can fix this issue?

Any help would be greatly appreciated!  Thanks in advance!

**Comment by jsonProgram** [comment]
you can install by conda, like :

conda install -c bioconda blast

**Comment by jsonProgram** [comment]
you can find dustmaster in your conda env

**Comment by lewhiteside** [comment]
Great thank you!
