### ISSUE TITLE
Print (un)classified sequences

### ISSUE THREAD

**Issue by namnh7** [DaehwanKimLab/centrifuge#243]
Hi there,

Could anyone tell me how to print unclassified/classified sequences in fastq (or fastq.gz) format.  My input are paired-end reads in **_file_1/2.fq.gz_**. 

Thanks for helping!

**Comment by rwhetten** [comment]
The `--un-conc <path>` option is supposed to "write pairs that didn't align concordantly to the designated path. If -gz or -bz2 is appended, e.g. `--un-conc-gz <path>`, output will be written in the corresponding compressed format.
