### ISSUE TITLE
ERROR): Expected centrifuge to be in same directory with centrifuge-class:

### ISSUE THREAD

**Issue by Bioinformatics-proj-k** [DaehwanKimLab/centrifuge#269]
Hi, 
I am trying to install latest version of centrifuge V 1.0.4.1 but for some reason centrifuge-class is missing in both tar and zip file. So I m keep getting error message: ERROR): Expected centrifuge to be in same directory with centrifuge-class:
So I copy the centrifuge-class from previous version to this new version.
Is there better way to make it run ?

Also I already refer issue #203.

**Comment by mourisl** [comment]
Have you run "make" to compile centrifuge? "centrifuge" is a perl-script wrapper, and you need to compile Centrifuge first.
