### ISSUE TITLE
Database question

### ISSUE THREAD

**Issue by SergeyBaikal** [DaehwanKimLab/centrifuge#271]
Dear developers!
When downloading databases, I was not able to download all sequences the first time. So I restarted and downloaded them again. I see more downloaded files in the catalog than there are in the list. Will this affect the working? And won't there be duplicates?
![Q](https://github.com/DaehwanKimLab/centrifuge/assets/47104608/1894ce3b-2139-4f7c-9cac-a3e2adb8878e)

`centrifuge-download -o library -m -d "archaea,bacteria,viral" refseq > seqid2taxid.map`

```
centrifuge --version
/usr/local/bin/centrifuge-class version 1.0.4
64-bit
Built on debian
Mon 26 Feb 23:56:16 GMT 2024
Compiler: gcc version 8.3.0 (Debian 8.3.0-7) 
Options: -O3 -m64 -msse2 -funroll-loops -g3 -std=c++11 -DPOPCNT_CAPABILITY
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
```

**Comment by SergeyBaikal** [comment]
Yes. This file is downloaded anew each time.

**Comment by mourisl** [comment]
Could you please share the file with me? I'll check which columns is misformatted.

**Comment by SergeyBaikal** [comment]
Yes, of course. Attached. 
[assembly_summary.txt](https://github.com/DaehwanKimLab/centrifuge/files/14475219/assembly_summary.txt)

**Comment by mourisl** [comment]
Ah, I thought the GCF.., 1_ViralProj14133 were different files, but they are just file name got wrapped. Can you send the list of the downloaded file names? I can do a cross-reference of those files with the assembly_summary file. Thank you.

**Comment by SergeyBaikal** [comment]
I attach a list of all downloaded file names in the directory.

[flist.txt](https://github.com/DaehwanKimLab/centrifuge/files/14475667/flist.txt)

**Comment by mourisl** [comment]
Thank you for sharing the files. It seems the extra files are the fasta files before dustmasker. You can "cat library/*/*dustmasked.fna > input-sequences.fna" to create the concatenated file for centrifuge-build. 

It is strange that the raw fasta file before dustmasking should be remove. Could you please check whether the file GCF_902141595.1_P2_4B2_genomic and its dustmasked version, GCF_902141595.1_P2_4B2_genomic_dustmasked.fna, have the same number of nucleotides? It's possible that the dustmasker failed on this sample somehow.

**Comment by SergeyBaikal** [comment]
The number of nucleotides of these two sequences is the same. For some reason the files before dustmasking were not deleted, although I tried the `chmod 777 `command. The file input-sequences.fna now contains 105575 sequences.

But I didn't have enough memory to build the index (80 Гб). 
`centrifuge-build -p 8 --conversion-table seqid2taxid.map --taxonomy-tree taxonomy/nodes.dmp --name-table taxonomy/names.dmp input-sequences.fna abv`  

I tried running on a cluster and installed centrifuge, but got an error.

```
~/centrifuge$ make
/usr/bin/g++  -O3 -m64 -msse2 -funroll-loops -g3 -std=c++11 -DCOMPILER_OPTIONS="            \"-O3 -m64 -msse2 -funroll-loops -g3 -std=c++11 -DPOPCNT_CAPABILITY\"" -DPOPCNT_            CAPABILITY \
-fno-strict-aliasing -DCENTRIFUGE_VERSION="\"1.0.4\"" -DBUILD_HOST="\"`hostname`            \"" -DBUILD_TIME="\"`date`\"" -DCOMPILER_VERSION="\"`/usr/bin/g++  -v 2>&1 | tai            l -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE   -DBOWTIE_MM              -DCENTRIFUGE -DBOWTIE2 -DBOWTIE_64BIT_INDEX -DNDEBUG -Wall \
-I third_party \
-o centrifuge-build-bin centrifuge_build.cpp \
ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp bt2_idx.cpp reference.            cpp ds.cpp limit.cpp random_source.cpp tinythread.cpp diff_sample.cpp centrifuge            _build_main.cpp \
-lpthread
In file included from bt2_idx.h:62,
                 from centrifuge_build.cpp:27:
processor_support.h:52:22: error: extended character “ is not valid in an identi            fier
   52 |         std::cerr << “ERROR: please define __cpuid() for this build.\n”;
      |                      ^
processor_support.h:52:70: error: extended character ” is not valid in an identi            fier
   52 |        std::cerr << “ERROR: please define __cpuid() for this build.\n”;
      |                                                                     ^

In file included from bt2_idx.h:62,
                 from bt2_idx.cpp:25:
processor_support.h:52:22: error: extended character “ is not valid in an identi            fier
   52 |         std::cerr << “ERROR: please define __cpuid() for this build.\n”;
      |                      ^
processor_support.h:52:70: error: extended character ” is not valid in an identi            fier
   52 |        std::cerr << “ERROR: please define __cpuid() for this build.\n”;
      |                                                                     ^

make: *** [Makefile:281: centrifuge-build-bin] Error 1
potapovs@linbio:~/centrifuge$ [Makefile:281: centrifuge-build-bin] Error 1
 [Makefile:281: centrifuge-build-bin] Error 1
```

**Comment by mourisl** [comment]
As long as you don't include those files in the concatenated fasta file that is the input for centrifuge-build, I think it should be fine.

**Comment by SergeyBaikal** [comment]
Thank you for helping me understand. Problem solved.
