### ISSUE TITLE
how do i setup the SILVA database?

### ISSUE THREAD

**Issue by davidmadariaga** [DaehwanKimLab/centrifuge#277]
Hi, im a noobioinformatician, how can i setup the SILVA database?¿ i just downloaded "Ref NR 99" from https://www.arb-silva.de/download/arb-files/ but i dont know what else to do now. Please help DDD:, i just want to do this "
"for files in *-trim.fastq
do
prefix=$(basename $files -trim.fastq)
centrifuge -q -x ~/Databases/silva138/silva138 "$files" -S ${prefix}-silva-full.tsv --report-file ${prefix}-silva-summary.tsv --min-totallen 800 -p 30
done

for files in *-silva-full.tsv
do
prefix=$(basename $files -silva-full.tsv)
centrifuge-kreport -x ~/Databases/silva138/silva138 "$files" > ${prefix}-silva-kraken.csv
done"

this was a script i was previously running on a server but that server was shut down, so now im kind of lost.
I would be deeply thankful if you can help me in some way.

greetings from Chile!

**Comment by mourisl** [comment]
You need to create the index for the SILVA database first. We have created a script to download the necessary files for Centrifuge/Centrifuger at: https://github.com/mourisl/centrifuger/tree/master/indices . After getting the index, like silva138.{1,2,3,4}.cf, your original script should work.

**Comment by davidmadariaga** [comment]
THAANKS, i'll try :DD

**Comment by davidmadariaga** [comment]
i just run the perl script for the silva database, thanks. Sorry for being stupid but what should i do now? i mean, i installed centrifuge using this "git clone https://github.com/DaehwanKimLab/centrifuge
cd centrifuge
make
sudo make install prefix=/usr/local"  im also now building the index with "make p_compressed " but honestly i dont know what should i do now, im sorry for wasting your time T.T

**Comment by davidmadariaga** [comment]
ITS DONE! i managed to do it:D using chatgpt hahaha, thanks for the help! your comment was crucial to do it :DDD thanks thanks

**Comment by davidmadariaga** [comment]
ITS DONE! i managed to do it:D using chatgpt hahaha, thanks for the help! your comment was crucial to do it :DDD thanks thanks
