### ISSUE TITLE
Couldn't find parent of taxID 138 - directly assigned to root.

### ISSUE THREAD

**Issue by davidmadariaga** [DaehwanKimLab/centrifuge#278]
Hi!, hope you are doing great. 

i downloaded the SILVA database with:

centrifuge-download -o taxonomy taxonomy
centrifuge-download -o library -m -d "bacteria" refseq > seqid2taxid.map

then I set up the database using this ./centrifuge-build-bin -p 4 --conversion-table silva_seqid_to_taxid.map --taxonomy-tree nodes.dmp --name-table names.dmp silva_seq.fa silva_16S_index

then run this script: 

do
prefix=$(basename $files -trim.fastq)
centrifuge -q -x /home/bioren/mdavid/centrifuge/centrifuge/silva_16S_index "$files" -S ${prefix}-silva-full.tsv --report-file ${prefix}-silva-summary.tsv --min-totallen 800 -p 30
done

and got the two output files correctly, eg, like everything is perfect:
![image](https://github.com/DaehwanKimLab/centrifuge/assets/25496906/cead3b49-ccc3-475f-80be-a6db36198876)

but when im using this script:

for files in *-silva-full.tsv
do
prefix=$(basename $files -silva-full.tsv)
centrifuge-kreport -x /home/bioren/mdavid/centrifuge/centrifuge/silva_16S_index "$files" > ${prefix}-silva-kraken.csv
done

im getting a output file empty that's giving me this message " Couldn't find parent of taxID 138 - directly assigned to root" repeatedly in the terminal. Also, the "...silva-kraken.csv" file is empty, like this:

 0	0	0	U	0	unclassified
32.06	4426	4426	-	1	root

feel free to answer whenever you can and if you can

cheers from Chile

**Comment by davidmadariaga** [comment]
Thanks for answering!!!!! 🥰 and for your time😀

**Comment by mourisl** [comment]
I have updated the script at: https://github.com/mourisl/centrifuger/tree/master/indices/silve-download.pl. Could you please give it a try? Thank you!

**Comment by davidmadariaga** [comment]
Hi!, i just run it: 

it gave me this error: 

[mdavid@mapudungun-frontend centrifuge]$ perl silva-download.pl 
Bareword found where operator expected at silva-download.pl line 11, near "data"
	(Missing semicolon on previous line?)
Bareword found where operator expected at silva-download.pl line 11, near ""auto" data"
	(Missing operator before data?)
Bareword found where operator expected at silva-download.pl line 11, near ""light" data"
	(Missing operator before data?)
Bareword found where operator expected at silva-download.pl line 12, near "data"
	(Missing semicolon on previous line?)
Bareword found where operator expected at silva-download.pl line 12, near ""system" data"
	(Missing operator before data?)
Bareword found where operator expected at silva-download.pl line 39, near "" src="https"
	(Missing operator before https?)
Bareword found where operator expected at silva-download.pl line 39, near "74354d43143c"
	(Missing operator before d43143c?)
String found where operator expected at silva-download.pl line 39, near "<script crossorigin=""
	(Missing semicolon on previous line?)
Bareword found where operator expected at silva-download.pl line 40, near "<script crossorigin="anonymous"
  (Might be a runaway multi-line "" string starting on line 39)
	(Missing operator before anonymous?)
String found where operator expected at silva-download.pl line 40, near "anonymous" defer=""
Bareword found where operator expected at silva-download.pl line 40, near "" defer="defer"
	(Missing operator before defer?)
String found where operator expected at silva-download.pl line 40, near "defer" type=""
Bareword found where operator expected at silva-download.pl line 40, near "" type="application"
	(Missing operator before application?)
String found where operator expected at silva-download.pl line 40, near "javascript" src=""
Bareword found where operator expected at silva-download.pl line 40, near "" src="https"
	(Missing operator before https?)
Can't modify numeric lt (<) in scalar assignment at silva-download.pl line 11, near "data"
syntax error at silva-download.pl line 11, near "data"
Unknown regexp modifier "/j" at silva-download.pl line 39, at end of line
Unknown regexp modifier "/v" at silva-download.pl line 39, at end of line
Unknown regexp modifier "/r" at silva-download.pl line 39, at end of line
Unknown regexp modifier "/t" at silva-download.pl line 39, at end of line
Unknown regexp modifier "/t" at silva-download.pl line 39, at end of line
Unknown regexp modifier "/h" at silva-download.pl line 39, at end of line
Unknown regexp modifier "/b" at silva-download.pl line 39, at end of line
Unknown regexp modifier "/t" at silva-download.pl line 40, at end of line
silva-download.pl has too many errors.

**Comment by mourisl** [comment]
It seems what you downloaded from the github is not the script itself but the link information. I guess you used "wget" on the link. You can use "git pull" to update the script if you previously used git clone.

**Comment by davidmadariaga** [comment]
thanks, now it works! thanks thanks thanks

**Comment by Sinceter** [comment]
<img width="965" alt="image" src="https://github.com/user-attachments/assets/be146c37-5426-4e91-a0b4-2b6fb2710219">
hi @mourisl , thanks for your contribution! 
I've faced the same issue as @davidmadariaga , i find the link above https://github.com/mourisl/centrifuger/tree/master/indices/silve-download.pl invalid, do you mind giving a new link to try on this solution?

**Comment by mourisl** [comment]
There was a typo, the link should be: https://github.com/mourisl/centrifuger/blob/master/indices/silva-download.pl . That script is part of the github repo of Centrifuger, you have to use "git clone" to get the repo and copy out the perl script. The other approach is to open the link and then download the script manually.

**Comment by Sinceter** [comment]
sorry, I made a mistake that we do not use silva database, we use refseq database and we store it in CENTRIFUGE_DB="/home/k/20-database/centrifuge_db/centrifuge_database". Then we run centrifuge-kreport -x "$CENTRIFUGE_DB" "20220308_nohuman_barcode08.fastq.gz_classifications.txt", and we get the aforementioned error 

> <img alt="image" width="965" src="https://private-user-images.githubusercontent.com/88071472/385576758-be146c37-5426-4e91-a0b4-2b6fb2710219.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NzEyMDUsIm5iZiI6MTczMTQ3MDkwNSwicGF0aCI6Ii84ODA3MTQ3Mi8zODU1NzY3NTgtYmUxNDZjMzctNTQyNi00ZTkxLWEwYjQtMmI2ZmIyNzEwMjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA0MDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkM2Q5MGM1NmJiNmViNmNlM2JlMjdkMmMyNmYzY2MzMWY0YTIyNjcyYjk1ZDMyMjBjZTU3OTdiNDA3YzEwOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IusMnu5M_KxMxWsS36wnRPnhIh9eYy6E7qsn4FjcEJs"> hi @mourisl , thanks for your contribution! I've faced the same issue as @davidmadariaga , i find the link above https://github.com/mourisl/centrifuger/tree/master/indices/silve-download.pl invalid, do you mind giving a new link to try on this solution?

**Comment by Sinceter** [comment]
And i checked the taxon directly assigned to root are not deprecated.

**Comment by mourisl** [comment]
Can you use "centrifuge-inspect" to check the tree in the index? The warning message about "Could not find parent node of 9606" is definitely strange, as the homo sapience should be well represented in the tree.

**Comment by Sinceter** [comment]
> Can you use "centrifuge-inspect" to check the tree in the index? The warning message about "Could not find parent node of 9606" is definitely strange, as the homo sapience should be well represented in the tree.

<img width="1275" alt="image" src="https://github.com/user-attachments/assets/c88c5ec7-35e9-487f-8e89-50bbdaa12667">
should it be like this?

**Comment by mourisl** [comment]
Right. Seems 9606 should be in the index. What were your running commands of centrifuge and centrifuge-kreport?

**Comment by Sinceter** [comment]
<img width="1160" alt="image" src="https://github.com/user-attachments/assets/4ff3c5f5-1103-4da6-bce1-6b7f2e3d60fa">
<img width="1265" alt="image" src="https://github.com/user-attachments/assets/d2e1b14c-8b2d-48d7-b8ca-055c8863323a">
Here

**Comment by mourisl** [comment]
I think you missed the dollar sign ($) before the "CENTRIFUGE_DB" variable when running centrifuge-kreport, so it actually did not load the index and everything was put to the root.

**Comment by Sinceter** [comment]
<img width="855" alt="image" src="https://github.com/user-attachments/assets/d294ab81-ce6c-4e83-8899-d335f41e1abf">
<img width="651" alt="image" src="https://github.com/user-attachments/assets/a23cef15-9eda-4996-abc1-b7d686d2d021">
no, sorry, it was a typo, it didnt work in the right command

**Comment by mourisl** [comment]
The error message looks like the index file is not there. Do you see any message like "Could not locate a Centrifuge index ..." in the running log?

**Comment by Sinceter** [comment]
I think I know where the problem is, thank you so much!
